GET http://localhost:8081/service



GET http://localhost:8080/sync?newHost=http://localhost:8081



GET http://localhost:8080/sync?sync=1&origin=http://localhost:8081



POST  http://localhost:8081/articles
Content-Type: application/xml

<ArrayList>
  <item>
    <authorFullName>ZZZZZZZZAuthorFN22</authorFullName>
    <title>Hello</title>
    <content>Content ...</content>
    <category>category</category>
  </item>
    <item>
    <authorFullName>AuthorFN33</authorFullName>
    <title>Hello</title>
    <content>Content ...</content>
    <category>category</category>
  </item>
    <item>
    <authorFullName>AuthorFN44</authorFullName>
    <title>Hello</title>
    <content>Content ...</content>
    <category>category</category>
  </item>
</ArrayList>



POST http://localhost:8081/articles
Content-Type: application/json

[
  {
    "authorFullName":"AuthorFN1",
    "title":"Hello134134",
    "content":"Content134134 ...",
    "category":"category134"
  },
  {
    "authorFullName":"AuthorFN2",
    "title":"Hello",
    "content":"Contentdafadfdaf ...",
    "category":"categorydafadfaddaf"
  },
  {
    "authorFullName":"AuthorFN3",
    "title":"Hello",
    "content":"Contentdafadfadfadf ...",
    "category":"categoryadfadfadf"
  },
  {
    "authorFullName":"AutdafadhorFN4",
    "title":"Helloadfadfadf",
    "content":"Contentadfadf ...",
    "category":"categorydafad"
  }
]


POST http://localhost:8082/service
Target: http://localhost:8081
Content-Type: application/json

GET  http://localhost:8082/articles?offset=0&limit=15
Content-Type: application/json

GET http://localhost:8081/articles?id=10
Content-Type: application/xml

DELETE http://localhost:8081/articles

2

GET http://localhost:8081/articles?offset=1&limit=5
Content-Type: application/xml

GET http://localhost:8081/articles?id=2
Content-Type: application/xml

PUT http://localhost:8081/articles
Content-Type: application/json

{
  "id": 10,
  "authorFullName":"ZZ",
  "title":"ee",
  "content":"rr ...",
  "category":"tt"
}

PUT  http://localhost:8081/articles
Content-Type: application/xml

<item>
  <id>2</id>
  <authorFullName>q</authorFullName>
  <title>w: </title>
  <content>w:  ...</content>
  <category>w</category>
</item>


OPTIONS http://localhost:8081/articles?delayInMilliseconds=30000



