GET http://localhost:8080/service



GET http://localhost:8081/articles?q=1&q=22
Content-Type: application/json



POST  http://localhost:8081/articles?q=1&q=22
Content-Type: application/xml

<ArrayList>
  <item>
    <authorFullName>AuthorFN22</authorFullName>
    <title>Hello</title>
    <content>Content ...</content>
    <category>category</category>
  </item>
    <item>
    <authorFullName>AuthorFN33</authorFullName>
    <title>Hello</title>
    <content>Content ...</content>
    <category>category</category>
  </item>
    <item>
    <authorFullName>AuthorFN44</authorFullName>
    <title>Hello</title>
    <content>Content ...</content>
    <category>category</category>
  </item>
</ArrayList>



POST http://localhost:8081/articles
Content-Type: application/json

[
  {
    "authorFullName":"AuthorFN1",
    "title":"Hello134134",
    "content":"Content134134 ...",
    "category":"category134"
  },
  {
    "authorFullName":"AuthorFN2",
    "title":"Hello",
    "content":"Contentdafadfdaf ...",
    "category":"categorydafadfaddaf"
  },
  {
    "authorFullName":"AuthorFN3",
    "title":"Hello",
    "content":"Contentdafadfadfadf ...",
    "category":"categoryadfadfadf"
  },
  {
    "authorFullName":"AutdafadhorFN4",
    "title":"Helloadfadfadf",
    "content":"Contentadfadf ...",
    "category":"categorydafad"
  }
]


GET http://localhost:8081/articles?offset=1&limit=5
Content-Type: application/json

GET http://localhost:8081/articles?id=11
Content-Type: application/json


GET http://localhost:8081/articles?offset=1&limit=5
Content-Type: application/xml

GET http://localhost:8081/articles?id=2
Content-Type: application/xml

PUT http://localhost:8081/articles
Content-Type: application/json

{
  "id": 1,
  "authorFullName":"ww",
  "title":"ee",
  "content":"rr ...",
  "category":"tt"
}

PUT  http://localhost:8081/articles
Content-Type: application/xml

<item>
  <id>2</id>
  <authorFullName>q</authorFullName>
  <title>w: </title>
  <content>w:  ...</content>
  <category>w</category>
</item>


OPTIONS http://localhost:8081/articles?delayInMilliseconds=3000
